name: vehiclereservation_frontend_flutter_
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_gallery_saver_plus: ^4.0.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.1.11
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  socket_io_client: ^2.0.3
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^17.1.1
  get: ^4.6.5
  json_annotation: ^4.8.1
  timeago: ^3.2.2
  location: ^5.0.0  # Add this for location services

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Icon.png
    - assets/images/Icon_half.png
    - assets/.env